// ---------- DATA ----------
const DESCRIPTIVES = [...];
const CORR_CGPA = [...];
const CORR_WELL = [...];
const CORR_MATRIX = {...};
const REG_CGPA = {...};
const REG_WELL = {...};
const FREQ = {...};
const LABELS = {...};